### ISSUE TITLE
Menu item does not appear after launching Xcode 6.3

### ISSUE THREAD

**Issue by harryzjm** [fortinmike/XcodeBoost#37]

**Comment by damuro** [comment]
With Alcatraz it works, but you must uninstall and install the plugin again every time you restart Xcode.

**Comment by harryzjm** [comment]
Thanks for your reply :)

**Comment by fortinmike** [comment]
This is definitely a bug. A reinstall with Alcatraz shouldn't be required after each Xcode restart; only when new major versions of Xcode are released. Thanks for tracking this down, @damuro, and for reporting, @harryzjm !

**Comment by fortinmike** [comment]
Fixed in 9fcc6bc. A reinstall through Alcatraz should ensure the plugin starts when Xcode is launched.

It seems that Alcatraz ignores compatibility UUIDs when loading Xcode plugins into the running app, which is why it worked when reinstalling through Alcatraz and didn't when Xcode was restarted afterwards (as Xcode does check compatibility UUIDs before loading plugins).
