### ISSUE TITLE
Xcode 7 reinstall needed after each startup

### ISSUE THREAD

**Issue by Dudi00** [fortinmike/XcodeBoost#42]
As title goes. After each xcode restart, reinstall of this plugin is needed.

**Comment by fortinmike** [comment]
Sorry for the delay. This is most probably due to not having the latest Xcode installed (or at least a version of Xcode that XcodeBoost explicitly lists as supported). I bet you installed the plugin with Alcatraz, which if I remember well dynamically load plugins regardless of their declared compatibility UUIDs.

With this setup, Alcatraz would inject the plugin in the running Xcode on install (while it's still running), then when Xcode is restarted it won't load the plugin because it doesn't declare the right compatibility UUID.

In essence, just install the latest Xcode, or a version that has its compatibility UUID [declared as supported by XcodeBoost](https://github.com/fortinmike/XcodeBoost/blob/master/XcodeBoost/XcodeBoost-Info.plist) and everything should work properly.

**Comment by Dudi00** [comment]
Hey, so new xcode released. How I can make Xcodeboost to work with new version. Your pluging is addictive :)

**Comment by fortinmike** [comment]
I'm glad the plugin is useful!

I just added the Xcode 7.2 compatibility UUID to XcodeBoost. You should just reinstall XcodeBoost from Alcatraz and it should work.

I'll gladly accept pull requests adding compatibility UUIDs. You can obtain the current Xcode compatibility UUID by looking at the system.log file in Console.app. Here's an example for the just-added UUID: 3a059363ee50f4d92fd93d9b93a6a72284942b85

**Comment by Dudi00** [comment]
Many thanks for that tutorial, to be honest I was looking for it :+1:
